# Generated by Django 3.1.1 on 2020-09-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_string', models.CharField(max_length=50, unique=True)),
                ('participants', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('shares', models.TextField()),
                ('orginal_image', models.ImageField(upload_to='original_images')),
            ],
        ),
    ]
